appVersion: latest
image:
  app: ghcr.io/tim-hat-die-hand-an-der-maus/telegram-bot

cronjobs:
  movie:
    name: which-movie-poll
    args: [ "poll" ]
    schedule: "0 19 * * 5"
    resources:
      requests:
        cpu: 300m
        memory: 100Mi
      limits:
        cpu: 300m
        memory: 300Mi
  participation:
    name: participation-poll
    args: [ "participation-poll" ]
    schedule: "0 16 * * 0"
    resources:
      requests:
        cpu: 300m
        memory: 100Mi
      limits:
        cpu: 300m
        memory: 300Mi

configmap:
  chatId: "-1001556735505"
  woStreamBaseUrl: "http://streamingprovider-resolver"
