[package]
name = "timhatdiehandandermaus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "timhatdiehandandermaus"

[lib]
name = "timhatdiehandandermaus"

[dependencies]
anyhow = "1.0.51"
teloxide = { version = "0.5.3", features = ["macros", "auto-send"] }
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros"] }
log = "0.4.8"
pretty_env_logger = "0.4.0"
thiserror = "1.0.30"
reqwest = { version = "0.11.7", features=["blocking"] }
url = "2.2.2"
serde = "1.0.131"
serde_json = "1.0.73"
serde_derive = "1.0.131"
teloxide-core = "0.3.4"
futures = "0.3.18"
futures-util = "0.3.18"
async-std = "1.10.0"
