[package]
name = "timhatdiehandandermaus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
teloxide = { version = "0.5.3", features = ["macros", "auto-send"] }
log = "0.4.14"
tokio = { version = "1.13.0", features = ["rt-multi-thread", "macros"] }
pretty_env_logger = "0.4.0"
thiserror = "1.0.30"
tempdir = "0.3.7"
reqwest = { version = "0.11.6", features=["blocking"] }
url = "2.2.2"
serde = "1.0.130"
serde_json = "1.0.70"
serde_derive = "1.0.130"
