namespace: timhatdiehandandermaus

deployment:
  name: telegram-bot
  image: ghcr.io/tim-hat-die-hand-an-der-maus/telegram-bot:__TAG__
  imagePullPolicy: Always
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: telegram-bot
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

configmap:
  name: telegram-bot-config
  botName: "watchqueuebot"
  baseUrl: "http://api"
  adminChat: "-1001556735505"

secret:
  name: telegram-token
  telegramToken: __TELEGRAM_TOKEN__
