namespace: timhatdiehandandermaus

deployment:
  name: telegram-bot
  image: ghcr.io/tim-hat-die-hand-an-der-maus/telegram-bot:__TAG__
  imagePullPolicy: Always
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: telegram-bot
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

cronjob:
  name: telegram-bot-which-movie-poll
  image: ghcr.io/tim-hat-die-hand-an-der-maus/telegram-bot:__TAG__
  imagePullPolicy: Always
  command: [ '"/app/timhatdiehandandermaus"' ]
  args: [ '"poll"' ]
  schedule: "CRON_TZ=Europe/Berlin 0 20 * * */5"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: telegram-bot-poll
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

poll:
  defaultOptions: "Nicht dabei,Mir egal"

configmap:
  name: telegram-bot-config
  botName: "watchqueuebot"
  baseUrl: "https://api.timhatdiehandandermaus.consulting"
  adminChat: "-1001556735505"

secret:
  name: telegram-token
  telegramToken: __TELEGRAM_TOKEN__
