---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      serviceAccountName: bot
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 256Mi
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bot
spec:
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: bot
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats-headless.nats-system.svc.cluster.local:8222"
        account: "$G"
        stream: "telegram-updates"
        consumer: "tim-telegram-bot"
