apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  API_URL: "{{ .Values.configmap.baseUrl }}"
  POLL_DEFAULT_OPTIONS: "{{ .Values.poll.defaultOptions }}"
  WOSTREAM_BASE_URL: "{{ .Values.configmap.woStreamBaseUrl }}"
  POLL_CHAT_ID: "{{ .Values.configmap.chatId }}"
