apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  secretStoreRef:
    name: scaleway-tim-bot
    kind: ClusterSecretStore
  target:
    name: secrets
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: "name:sentry-dsn"
        decodingStrategy: None
  dataFrom:
    - extract:
        key: "name:manual-secrets"
        decodingStrategy: None
