apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  secretStoreRef:
    name: doppler-tim
    kind: ClusterSecretStore
  target:
    name: secrets
  dataFrom:
    - find:
        path: "BOT_"
      rewrite:
        - regexp:
            source: "BOT_(.+)"
            target: "$1"
