apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: timhatdiehandandermaus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: ghcr.io/tim-hat-die-hand-an-der-maus/telegram-bot:{{tag}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: telegram-token
            - configMapRef:
                name: telegram-bot-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram-bot-config
  namespace: timhatdiehandandermaus
data:
  BOT_NAME: "timhatdiehandandermausbot"
  BASE_URL: "http://api"
  ADMIN_CHAT: "-766365181"
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-token
  namespace: timhatdiehandandermaus
data:
  TELOXIDE_TOKEN: "__TELEGRAM_TOKEN__"
