apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.participation.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.participation.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.participation.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.participation.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- range $k, $v := .Values.cronjob.participation.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.participation.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.cronjob.participation.restartPolicy }}
          containers:
          - name: {{ .Values.cronjob.participation.name }}
            image: {{ .Values.cronjob.participation.image }}
            imagePullPolicy: {{ .Values.cronjob.participation.imagePullPolicy }}
            command: {{ .Values.cronjob.participation.command }}
            args: {{ .Values.cronjob.participation.args }}
            envFrom:
              - secretRef:
                  name: {{ .Values.secret.name }}
              - configMapRef:
                  name: {{ .Values.configmap.name }}
            resources:
              requests:
                cpu: {{ .Values.cronjob.participation.requests.cpu }}
                memory: {{ .Values.cronjob.participation.requests.memory }}
              limits:
                cpu: {{ .Values.cronjob.participation.limit.cpu }}
                memory: {{ .Values.cronjob.participation.limit.memory }}
