apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.movie.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.movie.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.movie.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.movie.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- range $k, $v := .Values.cronjob.movie.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.movie.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.cronjob.movie.restartPolicy }}
          containers:
          - name: {{ .Values.cronjob.movie.name }}
            image: {{ .Values.cronjob.movie.image }}
            imagePullPolicy: {{ .Values.cronjob.movie.imagePullPolicy }}
            command: {{ .Values.cronjob.movie.command }}
            args: {{ .Values.cronjob.movie.args }}
            envFrom:
              - secretRef:
                  name: {{ .Values.secret.name }}
              - configMapRef:
                  name: {{ .Values.configmap.name }}
            resources:
              requests:
                cpu: {{ .Values.cronjob.movie.requests.cpu }}
                memory: {{ .Values.cronjob.movie.requests.memory }}
              limits:
                cpu: {{ .Values.cronjob.movie.limit.cpu }}
                memory: {{ .Values.cronjob.movie.limit.memory }}
