apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
stringData:
  API_TOKEN: "{{ .Values.secret.apiToken }}"
data:
  BOT_TOKEN: "{{ .Values.secret.telegramToken }}"
