name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy_production
    steps:
      - uses: actions/checkout@v3
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - name: update api token in manifest.yml
        run: sed -i -e "s#__API_TOKEN__#${{ secrets.API_TOKEN }}#g" values.yaml
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade telegram-bot . --install --namespace=timhatdiehandandermaus --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
